name: Angular CI/CD (Stockify)

on:
  push:
    branches: [ "main", "configuracion-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Linting
      run: npm run lint --if-present

    - name: Ejecutar Tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

    - name: Construir proyecto (Production Build)
      run: npm run build -- --configuration production

    - name: Subir Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: stockify-dist
        path: dist/stockify_frontend/